### ISSUE TITLE
Move Eventbus to Application scope rather request scope

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Orchard2#113]
We need to raise events tenant and application wide

**Comment by sebastienros** [comment]
I think there might be an issue if it's registered at a higher scope as it will resolve some services, and a singleton cannot resolve a scoped service.

**Comment by Jetski5822** [comment]
Yup, its a problem as we need to use the IEventBus everywhere... problem is that I really like its not currently reliant on Http.... hmmm need to have a think about this.

**Comment by GVX111** [comment]
I think EventBus must be registered in AddHostCore
<pre>  public static IServiceCollection AddHostCore(this IServiceCollection services) {
            services.AddSingleton<IClock, Clock>();

            services.AddSingleton<IOrchardHost, DefaultOrchardHost>();
            {
                services.AddScoped<IEventBus, DefaultOrchardEventBus>();
                services.AddSingleton<IEventBusState, EventBusState>();

                services.AddSingleton<IShellSettingsManager, ShellSettingsManager>();

                services.AddSingleton<IShellContextFactory, ShellContextFactory>();
                {
                    services.AddSingleton<ICompositionStrategy, CompositionStrategy>();
                    {
                        services.AddSingleton<IOrchardLibraryManager, OrchardLibraryManager>();
                    }

                    services.AddSingleton<IShellContainerFactory, ShellContainerFactory>();
                }
            }

            services.AddSingleton<IProcessingEngine, DefaultProcessingEngine>();

            services.AddSingleton<IRunningShellTable, RunningShellTable>();

            return services;
        }

**Comment by sebastienros** [comment]
You need to understand the difference between Application singletons and Tenant singletons. Application singletons are unique for all tenants, whereas Tenant singletons are unique inside a specific tenant. All the services which are registered using `services.AddSingleton` will be application singletons. All the `ISingleton` interfaces will be tenant singletongs. 

The EventBus state needs to be per tenant, because messages can't go across the tenant boundary, so the state needs to be defined on the tenant services collection, which is what `ShellContainerFactory` is building.

How application singletons are built is that they are resolved by `ShellContainerFactory`, and injected as instances in the tenant's container, as a singleton. So all the tenants will actually share the same instance.

What events need to be raised application wide?

Another solution is for the EventBus state to store the state for every tenant.
