### ISSUE TITLE
TagHelpers don't work anymore

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#121]
@jtkech I think you are the last one who touched this roslyn compilation after I had fixed it. If you try to add `@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"` to a view and use one of the tag helpers (like form) then it will complain about a reference missing. It means it's not adding the references that are in project.json.

**Comment by jtkech** [comment]
@sebastienros sorry, not sure how to test it, but i'll try to check it.

**Comment by jtkech** [comment]
@sebastienros where i am

With the latest source code i needed to re-run a fresh setup (i think because of shell descriptors). Then i've used the `http://localhost:5001/home/index` to hit the Orchard.Demo index view where i've added:

    @addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
    ...
    <form />

Then i've got the issue you described. But it's the same if i revert back the update related to the `DefaultRoslynCompilationService`. This e.g by re-adding the `references.AddRange()` in the `Compile()` method.

I continue to look further...

Best

**Comment by jtkech** [comment]
@sebastienros 

To get it working, i needed to add the `Microsoft.AspNet.Mvc.TagHelpers` assembly to the `Orchard.DisplayManagement` project. Indeed, this project uses this assembly.
