### ISSUE TITLE
In the Content Update events we should get more infos

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard2#136]
In the OnUpdating event we should get the old values but also the updated values (as a name-value list  may be).
And for the OnUpdated we should get the old (modified) values (as a name-value list).

**Comment by sebastienros** [comment]
What is the scenario for this? Based on what you are trying to achieve I think there would be better options.

The goal of this event is to let a component edit the values based on the editor. And each driver get the object, so the first one to be executed gets the _previous_ values. And the component can then save it for the updated event.

**Comment by CSurieux** [comment]
Happy to understand this.
In MS CRM there are sames event (in many systems in fact) and more in plugins.
They always send the list of before / after values, it allows very efficace (fe) data management, no system oriented.

**Comment by sebastienros** [comment]
Maybe they provide this because they don't have the same events as Orchard has. There is nothing which prevents you from getting the old value on demand, so whatever you would like to do with it is there, there is nothing to add. We could add everything, but in the handler you can get it by yourself if necessary.

You still haven't given me the scenario where it would make sense to have both initial and current values in the Updated method. Knowing that the Updating already has them as this is what is passed to it to be changed.

**Comment by CSurieux** [comment]
What you describe is much more complicated, everything to reinvent each time.
How to get the new values before they have been applied ?

I think in MSCRM they parse the request before sending the events.

**Comment by sebastienros** [comment]
Again, instead of trying to add features, we need to understand the need for this feature. So feel free to provide a scenario, if not a valid one.

> in MSCRM they parse the request before sending the events

What is the meaning on this sentence? Parsing the request? Sure, MVC parses the request. Every time.
