### ISSUE TITLE
Should zones have no tags

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#137]
Right now in `ZoneShapes`, as in O1 we render a `div` tag a `zone zone-name` classes for a layout zone.

I think we should render zone bare, and let the layout define how it is done. It's not harder anyway to define the tagging in the layout. but it much harder to remove the tag afterwards.
The ContentZone behavior would not be altered though.

**Comment by sebastienros** [comment]
@Piedone @DanielStolt @sfmskywalker @bleroy @BenedekFarkas @pszmyd I value your response on this one (not the others)

**Comment by bleroy** [comment]
Here's my answer: https://github.com/DecentCMS/DecentCMS/blob/master/modules/core/ui/views/zone.js

In other words, no, zones should not render a tag by default. First because it's just a container of shapes that has no other semantics. Second, because it is a shape that is rendered by a shape method and not a template, which makes it a little more complex to override. Even if it was a template, having to copy all the code looping over contents just to change the tag is an excessive burden.

But in doubt, it should just do nothing and let the layout template render a surrounding tag if it wants to. That makes it more discoverable how to change it.

We could also have a general purpose property for all shapes, in the metadata, to override the tag default (which would be null for zone). The layout would set that property to "div" if it wants a div to surround the zone, and this way it doesn't have to test for the shape's contents before it renders the tag. It can just let the zone shape do it.

**Comment by Piedone** [comment]
I'm also for the core behaviour being tag-less, but with a built-in (optional) way of them being enclosed in divs just like today.

Reason: I see the point of not coupling the shapes-related zone tightly with the HTML output-related tags. However in my experience I have never ever seen a case when it wasn't of utility to have zones wrapped into such divs by default (since zone classes are always used in CSS to target elements). So if zones will be bare IMO there should be a built-in way (like the default Layout) of providing the same experience as today (so you can start with something good enough that you can customize if you wish), even if it's different under the hood.

I'd value Sebastien's reply here (not otherwise).

**Comment by sebastienros** [comment]
I would say that if a theme wants to render zones differently you could create a `Zone.cshtml` file. Note that zones don't have to order their items as in O1 they just have to iterate through the `Items` and call render, so a template is minimalist in this case. At the same time I would personally just update the `Layout.cshtml` to add the desired tags. So I don't even see why I would use an option if there was one.

**Comment by DanielStolt** [comment]
I completely agree with tagless zones - one of the first things I do when theming is to override Zone.cshtml to remove the wrapping div. I really like @bleroy's idea adding a general purpose property for this to shapes, which would be null by default for zones.

**Comment by sfmskywalker** [comment]
No tag by default. The user can create a Zone.cshtml to provide a custom template. Initially I was thinking that adding a Tag metadata property may not be that useful. In many cases you'll want to change more than the tag when overriding shape templates. But metadata already has Classes and Attributes, so having a Tag property might complete the set for programmatic manipulation of shape rendering without having to override a template for simple scenarios. Wouldn't hurt to have it.

**Comment by sfmskywalker** [comment]
Correction, I meant to say that Classes and Attributes are properties on the `Shape` class. So we could introduce a `Tag` property there, or move these properties into `ShapeMetadata`. I think it makes sense for `Tag`, `Classes` and `Attributes` to be grouped together.

**Comment by CSurieux** [comment]
A general tagless policy seems necessary. O1 is too 'verbose'. Let's us alternates to add html if needed, Opposite way of O1.

**Comment by sebastienros** [comment]
@sfmskywalker It's already like this. c.f. https://github.com/OrchardCMS/Orchard2/blob/master/src/Orchard.DisplayManagement/Shapes/Shape.cs#L247-L253

Also there is how you use it from a view: https://github.com/OrchardCMS/Orchard2/blob/master/src/Orchard.Web/Core/Orchard.Core/Navigation/Views/Menu.cshtml#L2

**Comment by sebastienros** [comment]
Done
