### ISSUE TITLE
Error running build.cmd

### ISSUE THREAD

**Issue by jbraun27** [OrchardCMS/Orchard2#145]
Trying to clone and build the Orchard2 repo for the first time... running build.cmd gives an error that it is "unable to find package 'KoreBuild'". I get the same when running this:
.nuget\nuget.exe install KoreBuild -ExcludeVersion -o packages -nocache -pre
VS2015 and DNVM setup and installed... but I must be missing something.

**Comment by jeremycook** [comment]
I experienced the same issue trying orchard2 for the first time late last week. It seems that aspnet vnext/core is changing significantly and is Lumley causing this and then other issues once you get past this one. 

I know this doesn't help you per se but maybe it's good advice since all this tech is so new. I'm going to wait for aspnet core to buy rc2 before trying out orchard2.

**Comment by jbraun27** [comment]
Thanks @jeremycook that helps a lot actually. I thought that maybe I messed something up installing aspnet core for the first time. I'd like to get started with Orchard2 with some experimental sites, but don't have the resources to track down issues down to the vnext level right now.  Hopefully someone can come through here with a fix.

**Comment by alexbocharov** [comment]
Fixing build when you move to dotnet cli. [I make the transition to rc2](https://github.com/alexbocharov/Orchard2/tree/target-netcore-rc2l)

**Comment by alexbocharov** [comment]
@sebastienros @Jetski5822  Maybe create a branch **dev**? (To work on unstable code)
