### ISSUE TITLE
Consider removing "debugType": "portable" from project.json

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#235]
Forcing the debug type to "portable" prevents VS' debugger from working correctly (e.g some variables can't be introspected).

**Comment by sebastienros** [comment]
We are using `portable` as this is the only value that VS Code support to be enable debugging. The solution is to have VS Code use some specific configuration and use a default vallue of `full` (or no specific value as it will have the same effect).

There is currently no option to set `debug-type` from command line, the only way is to update ALL the `project.json` to add a `configuration` slot that uses portable pdbs, then VS Code `tasks.json` script to use this specific configuration in the `dotnet build` commands.

**Comment by sebastienros** [comment]
@jtkech I think you should comment on this issue while it's fresh in your mind why you need portable debug type.

**Comment by jtkech** [comment]
Ok, i'm preparing it.

**Comment by jtkech** [comment]
- So, @sebastienros was right about VS Code, this was the only way to be able to use the debugger.

- For an ambient project (part of the app) under VS we could use what we want, but here the problem is  to be compatible with VS Code because there is no avalaible option through the command line.

- That said, for a module / theme project which is dynamically compiled at runtime, we will force by code debugType: Portable, this because when using debugType: full, the csharp compiler detect it is e.g on a desktop and may try to use native assemblies we don't embed in our app. E.g in my dev env i got.

        Windows PDB writer is not available -- could not find Microsoft.DiaSymReader.Native.amd64.dll

- Maybe the same reason why VS Code debugger doesn't work with this option

- I've heard that portable debug infos will be improved (if not yet done in some points).

Let me know if it is worth to try something here.

Best.

**Comment by PinpointTownes** [comment]
Understood. I think I'll just write a tiny script removing `debugType: portable` from `project.json`, then ('cause not being able to debug local variables is... really annoying :smile:)

**Comment by PinpointTownes** [comment]
> Then about your script, bof, do you know VS has a search function ;)

I do. But doing that every time I need to debug some Orchard bits is going to be painful :smile:

**Comment by jtkech** [comment]
Just come back.

Just tried to put a breakpoint in a controller of Orchard.Demo, so in a module loaded at runtime and with debugType: portable, then i can see and expand local variables. As i remember it was the same with VS Code.

![vs debug](https://cloud.githubusercontent.com/assets/8586360/19133734/108b6180-8b5a-11e6-9105-216c5ac60c5b.png)


But interesting to see if something can be done to support full debug infos also for modules dynamically loaded when we are in a dev environment.

Best.

**Comment by PinpointTownes** [comment]
FWIW, here's what I get with `debugType: portable` when debugging the OAuth2 module:

![image](https://cloud.githubusercontent.com/assets/6998306/19134559/f3ae2552-8b5e-11e6-9f09-10b61b125515.png)

**Comment by jtkech** [comment]
Oh yes i see, maybe some options or some updated debug tools. I have VS 2015 update 3 an maybe some other updated tools i don't remember.

I will search on this and let you know my findings.

**Comment by jtkech** [comment]
So, maybe a solution

- Already ok for ambient projects belonging to the main app dependencies. So here only for modules and non ambient core projects which may be compiled at runtime as a dependency of a module.

- Use the `Microsoft.DiaSymReader.Native` package to be able to retrieve its native assets at runtime.

- If not on a windows platform, because full is not supported, force the portable option by code.

- Otherwise if the full option is specified, do the following if not already done.

- Store the native assets in the runtime directory at runtime. In a published context there are already there because of the referenced package, but we still need them in other contexts.

- Create a fake `csc.deps.json` to reference these native assets and to allow the compiler to found them.

- We need to do this because we execute the compiler as an independent process.

- When i do it manually it works, so i think it's doable.

If it is doable, will be ready next week.

Best.

**Comment by jtkech** [comment]
So because things begin to work

- The logic of dotnet is to check if there is no debug option, then if on windows use `full`, if not use `portable`. Otherwise use the provided option.

- Maybe wrong here because if the `full` option is provided it will not be compatible on a non windows platform where a different version would be needed.

- But i think it's better to do the same as dotnet and then, if it works, have the following rule.

- Never specify the `full` option, if we want it just specify nothing, then it will be used only on windows platforms. This only if what i'm trying to do works.

Let me know.

Best.
