### ISSUE TITLE
Use hosting environment setting instead of #DEBUG

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#254]
Here:
https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Web/Modules/Orchard.OpenId/Startup.cs#L84

So you don't need to rebuild to switch the behavior, also.

**Comment by PinpointTownes** [comment]
Related ticket: https://github.com/OrchardCMS/Orchard2/issues/243.

**Comment by jersiovic** [comment]
I'm fixing this issue and #243 with this code:

```

            if (_hostingEnvironment.IsDevelopment())
            {
                builder.DisableHttpsRequirement().AddEphemeralSigningKey();
            }
            else
            {
                X509Certificate2 certificate = GetCertificate(StoreName.My, StoreLocation.LocalMachine, thumbPrint: "099E363F65061986C9F327C3A1E8AA99CB3E739B");
                if (certificate == null)
                    _logger.LogError("Orchard.OpenId module needs you provide a valid signing certificate"); 
                else
                    builder.AddSigningCertificate(certificate);
            }
```

I want to make configurable storageName, storageLocation and thumbPrint parameters of GetCertificate method. I would add an entry in appsettings.json for those three parameters. Do you agree?

**Comment by PinpointTownes** [comment]
Sounds good :shipit: 

3 remarks, tho':

  - `AddEphemeralSigningKey()` is handy during development time, but note it won't work everywhere (for an example, read https://github.com/openiddict/openiddict-core/issues/204). Consider calling it only if the certificate details can't be found in appsettings.json.

  - OpenIddict has `AddSigningCertificate` helpers that allow you to specify the thumbprint and the store name/location. They will throw an `InvalidOperationException` if the certificate cannot be found.

  - OpenIddict will throw an exception if no signing certificate/key is registered, so even if you create your own "exceptionless" `GetCertificate` helper, it will later crash when calling `app.UseOpenIddict()`.

**Comment by PinpointTownes** [comment]
@jersiovic since you're updating the OpenID module, maybe you could also fix https://github.com/OrchardCMS/Orchard2/issues/276 too?

**Comment by sebastienros** [comment]
> I want to make configurable storageName, storageLocation and thumbPrint parameters of GetCertificate method.

Is this sufficient or is there any other real world way to of getting a certificate that is not `GetCertificate`? If not then I agree with the solution, otherwise we need to abstract how we read certificates a little more.( e.g. KeyVault, Linux, ...).

The same way we might want to change what logging provider has to be used, and has to be decided at the host level, so it can't be a module.

**Comment by PinpointTownes** [comment]
OpenIddict natively supports 4 ways to retrieve a certificate:

  - From the X.509 user/machine store: it's my favorite option, as it offers the best security experience (no password has to be provided and the worker process must be granted the right to access the private key).
  - From an embedded resource. It's convenient, but not really suitable in this case (specially since Orchard is meant to be multitenant)
  - From a file. This option would work with Orchard (it's currently how the OpenID module works), but extreme caution must be taken to make sure the certificate file is not remotely accessible (note: a password must be provided at runtime).
  - From an arbitrary blob: you can directly instantiate a `X509Certificate2` with the certificate bytes, so it can be stored everywhere you want (e.g in a config file or in a database).

On Linux, there's no "real X.509 user/machine store", but one is "emulated" by .NET Core - and presumably by Mono too - using good old directories, so there's nothing Linux-specific that should be implemented in the OpenID module.

Tho' OpenIddict doesn't natively integrate with Azure KeyVault, something similar to https://github.com/aspnet/DataProtection/pull/178 could be implemented.

**Comment by jersiovic** [comment]
@PinpointTownes ok I have assigned to me the #276

@sebastienros  When I tried to run Orchard 2 standalone (as a command or as a service) I faced problems because it is done to be run on IIS but other hosting environments like standalone hasd't been taken into account. So, I agree with what you propose. It is a better approach than coding directly what we need on each moment.

**Comment by sebastienros** [comment]
So this is not Host specific, but tenant specific as each tenant can have different implementations or configurations. However I don't think the stores would/should be different for each tenant, hence we could have a common way to provide the certificates for all tenants, at least with a convention for each way of doing so.

~~What about supporting all of them OOB, for instance first look for certificates in the store, with a name convention. First looking in the user store, then the machine store, looking for a tenant named certificate, then a default named certificate. If none is found then go to a specific certificates folder locally with a tenant name, and again to a common name.~~

We actually need some configuration as we need to pass in the thumprint at least. So let's provide the GetCertificate and File possibilities OOB, without making it extensible for now, and if a `certificates.json` is provided then load the configuration from it. Like we do for logging. This way you can also define the settings in environment variables. I let you propose a format, provided that we can define a common certificate (for all tenants) and specific ones. Or should all tenants ALWAYS have different certs?

With KeyVault the idea would be to copy the certificate during the deployment time, at a well known location. This is how it's done on public Azure services, only specific service accounts and machines have access to the certs, so no dev can even see them. The thumbprint is also set in the config during deployment.

**Comment by PinpointTownes** [comment]
> What about supporting all of them OOB, for instance first look for certificates in the store, with a name convention. First looking in the user store, then the machine store, looking for a tenant named certificate, then a default named certificate. If none is found then go to a specific certificates folder locally with a tenant name, and again to a common name.

Yeah, scratch that, it would be particularly fragile (searching certificates using the common name is definitely possible, but it seems weird to use the tenant name for that)

> Or should all tenants ALWAYS have different certs?

You've never really determined what's the approach you'd like to adopt: https://github.com/OrchardCMS/Orchard2/pull/215#r74472720

Currently, it uses the first approach (total isolation), so it would make sense to have a certificate per tenant (and ideally, it shouldn't be shared).

**Comment by jersiovic** [comment]
This issue was fixed setting Open Id configuration in db
