### ISSUE TITLE
Content fields

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#352]
Reminder: Recreate the Content fields that already exists in Orchard 1.

TextField: Add other options to make it more customizable.
BooleanField: We created a basic one.

InputField: Don't recreate it, try to only have the TextField.

DateTimeField: First implementation but will need Localization and Culture to finish it.

LinkField
NumericField
EnumerationField

If you want to work on one in particular, add a comment.

**Comment by agriffard** [comment]
I started to recreate the LinkField and I will commit soon in a 'fields' branch.

**Comment by sebastienros** [comment]
Can we talk about it at the meeting first? Bertrand has strong opinions on this, and I personally don't like some of the fields which are IMO too complex. I personally would like to see some of them split in different fields. And when I see "TextField: Add other options to make it more customizable" this is exactly what I don't want, for customizable, like I am afraid you will introduce "flavors".

It'd be better if you came if a list of fields and description of options for each. Feel free to look at other CMS for ideas.

**Comment by agriffard** [comment]
Link field settings would have these options:
- Hint
- Label
- Required
- TargetMode: None, NewWindow (_blank), Parent, Top, UserChoice
- LinkTextMode: Optional, Required, Static, Url
- StaticText: if LinkTextMode == Static
- UrlPlaceholder
- TextPlaceholder
- DefaultValue
- TextDefaultValue

Link field has these properties:
- Value of the url
- Text of the link
- Target: if TargetMode == UserChoice

**Comment by sebastienros** [comment]
At least we can agree on a minimum set of properties for each field:
- Hint
- Required
- DefaultValue (be explicit that this is the one used in the editor the first time it's displayed)

**Comment by agriffard** [comment]
For all fields, I'd like to have the ability to show or not the label on front, before the value.

To avoid a ShowLabel property, may be, we can add a Label property, different from the `@Model.PartFieldDefinition.DisplayName()` and we display on front `@Model.Field.Label@T[":"]` only it is not empty.

**Comment by sebastienros** [comment]
I was thinking about how we should be able to customize field rendering more generally. This issue is related to how themes should be built, so I was even thinking of a system where they are not rendered at all, you just edit a razor view to define the rendering. I don't see any correct way to render a field that will look like something you could want without altering the views themselves. Look at TheBlogTheme, we have two fields for each type, none of them could use the fields with just configuration to get them placed and rendered as expected. Not only that by it's more simple to just place the value where you want in a template than try to grasp all the configuration possibilities, and more performant too.

So I'd be up to provide no configuration at all, and be explicit on how to render a field by override the part template that owns it, it not the type template. We could make this easier with admin side templates, even more if they were to be located in the part/type settings views so it's easy to organize and more obvious to change.

Another option would be to support "display modes" like we have editors for editing them, so we could provide well-known ways to render a field. Like a youtube block for a link, or a linkable image, a code snippet for text fields, ... or a simple raw value. I would also personally love to change the placement from the settings instead of the placement file. The placement file would just be in themes then.

**Comment by agriffard** [comment]
These are all good ideas :
- Edit templates from the Admin side.
- Display modes (Drupal also has this concept for fields). 
- I'd go further for placement, even if I dream a little : Drag and drop + Preview positonning from admin.

Other possible enhancement for templating : 
- {{mustache}} syntax with handlebars or liquid.

**Comment by agriffard** [comment]
I tried CraftCms and they have many interesting fields.

There is also an important difference concerning the way you add and edit a field: 
In Orchard, the type of field is chosen depending on what kind of value we want to handle.
In CraftCms, the type of field is chosen depending on what kind of control will be displayed to the user.

Orchard is more 'developer or advanced user' centric and Craft has an approach easier to understand for a 'simple' user.
 
Ex: CraftCms has Checkboxes, RadioButtons, Dropdown and Multi-select fields while Orchard as an Enumeration field that allows to handle a list of items.

Here are some other equivalent fields between CraftCms and Orchard:
Assets => Media Library Picker		
Categories => Taxonomies
Date/Time => DateTime
Entries => Content Picker
LightSwitch => Boolean
Number => Numeric
Plain Text => Text
Rich text => Html

Matrix => Flow Part
Tags => Tags Part

And other that don't have an equivalent:
Position select
Table
Users

**Comment by agriffard** [comment]
See PR #650 for Numeric Field

**Comment by agriffard** [comment]
Closing. Will create specific issues by field.
