### ISSUE TITLE
Public OpenID client applications shouldn't be forced to register a redirect_uri/post_logout_redirect_uri

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#367]
Public clients who only want to use the password grant flow shouldn't have to register a fake redirect_uri/post_logout_redirect_uri: 

https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Cms.Web/Modules/Orchard.OpenId/Controllers/AdminController.cs#L174-L184

/cc @jersiovic

**Comment by jersiovic** [comment]
I only check those uris for ClientType.Public apps. Those as far as I understood will be apps that will use Authorization Code Flow. For Confidential apps (those that will use Client Credentials Flow and Password Flow) I don't check those uris because I thought they doesn't mind for those flows. In fact I hide its input field when the user is configuring the app as a Confidential app.
Can you point me in what am I wrong?

**Comment by PinpointTownes** [comment]
> Can you point me in what am I wrong?

The fact a client application is marked as "confidential" doesn't mean it can't use the authorization code flow or the implicit flow.

It would be better to allow the developer to list the flows an application can use and dynamically determine whether a redirect_uri should be provided (i.e if "authorization code"/"implicit flow"/"hybrid flow" is selected). A check could be added in `AccessController.Authorize/Exchange` to determine whether the request should be aborted, depending on the flows associated with the application.

**Comment by jersiovic** [comment]
Then, what I don't get is why OpenIddict differentiate between Confidential and Public apps? Does it makes any difference for Openiddict an app is marked as confidential or not?

**Comment by PinpointTownes** [comment]
> Does it makes any difference for Openiddict an app is marked as confidential or not?

Of course it does, otherwise it would make no sense to differentiate public and confidential apps :trollface: 

The main difference is that confidential applications MUST send their client_secret when communicating with the token and revocation endpoints. This "client authentication" step guarantees that only the legit client can exchange an authorization code or get a refresh token.

You can take a look at the unit tests to see how it works: https://github.com/openiddict/openiddict-core/blob/dev/test/OpenIddict.Core.Tests/Infrastructure/OpenIddictProviderTests.Exchange.cs#L222-L296

**Comment by PinpointTownes** [comment]
> In fact, if I'm not wrong with my memories I remember months ago that password flow fails if it was requested for a public app or sth like that.

Heh no... this scenario is supported since the very first day :smile:

**Comment by jersiovic** [comment]
Ok, I see.
Then I will reflect that on OpenId general settings, allowing the admin to set which flows are allowed, and adapting the required data to ask to the user when adding/editing an app.

**Comment by sebastienros** [comment]
Is the flow type settings specific to each app? If so it's not an openid setting, but an `Application` one.

**Comment by PinpointTownes** [comment]
There are two places where this kind of decision can be made: at startup time, using the `EnableXYZFlow(...)` extensions (which allows OpenIddict to expose the enabled flows via the discovery endpoint) and in the authorization controller, where additional per-application constraints can be implemented.

IMHO, it would make sense to use the two approaches (global + app-specific).

**Comment by jersiovic** [comment]
The new settings I'm planing to offer at global level are:

bool EnableTokenEndpoint
bool EnableAuthorizationEndpoint
bool EnableUserinfoEndpoint

User cannot change path of those endpoints, only decide if he want to enable each of them.
Depending on what the user choose for previous values he will see following options:
bool AllowPasswordFlow   (visible if EnableTokenEndpoint==true)
bool AllowClientCredentialsFlow  (visible if EnableTokenEndpoint==true)
bool AllowRefreshTokenFlow  (visible if EnableTokenEndpoint==true)
bool AllowAuthorizationCodeFlow  (visible if EnableAuthorizationEndpoint==true)

At openid-app level I will show only those:
bool AllowPasswordFlow  (visible if Global.AllowPasswordFlow  == true)
bool AllowClientCredentialsFlow  (visible if Global.AllowClientCredentialsFlow  == true)
bool AllowRefreshTokenFlow  (visible if Global.AllowRefreshTokenFlow  == true)
bool AllowAuthorizationCodeFlow (visible if Global.AllowAuthorizationCodeFlow == true)

Roles at app level only will be visible if AllowClientCredentialsFlow  == true

What do you think?

**Comment by PinpointTownes** [comment]
A few remarks:

> bool AllowAuthorizationCodeFlow (visible if EnableAuthorizationEndpoint==true)

Note: the authorization code flow requires enabling both the authorization endpoint and the token endpoint. OpenIddict will throw an `InvalidOperationException` when calling `app.UseOpenIddict()` if you enabled the code flow without configuring the two endpoints.

> Roles at app level only will be visible if AllowClientCredentialsFlow == true

Not sure what you mean by "app level" roles. Care to explain? :smile: 

Also, no option to enable the implicit flow?

**Comment by jersiovic** [comment]
Ah ok, so those will be the available options:

bool EnableTokenEndpoint
bool EnableAuthorizationEndpoint
bool EnableUserinfoEndpoint

User cannot change path of those endpoints, only decide if he want to enable each of them.
Depending on what the user choose for previous values he will see following options:
bool AllowPasswordFlow (visible if EnableTokenEndpoint==true)
bool AllowClientCredentialsFlow (visible if EnableTokenEndpoint==true)
bool AllowAuthorizationCodeFlow (visible if EnableAuthorizationEndpoint==true and  EnableTokenEndpoint==true)
**bool AllowRefreshTokenFlow (visible if EnableTokenEndpoint==true and (AllowPasswordFlow==true or AllowAuthorizationCodeFlow==true ))**
bool AllowImplicitFlow (visibleif EnableAuthorizationEndpoint == true)

At openid-app level I will show only those:
bool AllowPasswordFlow (visible if Global.AllowPasswordFlow == true)
bool AllowClientCredentialsFlow (visible if Global.AllowClientCredentialsFlow == true)
bool AllowRefreshTokenFlow (visible if Global.AllowRefreshTokenFlow == true)
bool AllowAuthorizationCodeFlow (visible if Global.AllowAuthorizationCodeFlow == true)
bool AllowImplicitFlow (visible if Global.AllowImplicitFlow == true)

Roles at app level only will be visible if AllowClientCredentialsFlow == true . Roles are the Orchard Roles assigned to the open id app to know which claims are related to that app. When no ClientCredentialsFlow is used this is not needed because claims assigned are those related to the authenticated user.

Keep an eye to the change I have made to conditions of visibility for Global.AllowRefreshTokenFlow

**Comment by PinpointTownes** [comment]
Sounds good 👍

**Comment by jersiovic** [comment]
@PinpointTownes I don't find an AllowHybridFlow extension for OpenIddictBuilder however in OpenIdConnectRequest there is  this method: IsHybridFlow().
How can be configured OpenIddict to allow or not HybridFlow when OpenIddictBuilder is configured?

**Comment by jersiovic** [comment]
@PinpointTownes more questions ...
As far as I know for Authorization Code Flow all tokens are returned from the Token Endpoint, however in AccessController.Token Action there is no code for handling Authorization Code Flow https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Cms.Web/Modules/Orchard.OpenId/Controllers/AccessController.cs#L48 If openiddict doesn't forward Authorization Code Flow requests to this action, then how is it supposed I can control if it is allowed based on the Open Id App configuration?
Maybe I need to update openiddict?

**Comment by PinpointTownes** [comment]
There's no standard `grant_type` value for the hybrid flow. The hybrid flow is automatically enabled when enabling both the authorization code flow and the implicit flow.

**Comment by PinpointTownes** [comment]
> how is it supposed I can control if it is allowed based on the Open Id App configuration?

Make this check in the authorization endpoint action.
