### ISSUE TITLE
View location expander for Viewcomponents and theme views

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#376]
Implement a correct priority list and list of discovered paths to handle ViewComponent and Controller views.

This is the current code in ModuleViewLocationExpander:

```
            // TODO: This is a dumb implementation in order to find the ViewComponent views when
            // it's called from a different module than the current controller.
            // This might also be enhanced to add support for Themes to override module controllers.
            
            foreach (var moduleId in _moduleIds)
            {
                result.Add("/Modules/" + moduleId + "/Views/{1}/{0}.cshtml");
                result.Add("/Modules/" + moduleId + "/Views/Shared/{0}.cshtml");
            }

```

**Comment by jtkech** [comment]
Oh, i missed this part.

- We also need to implement it for themes. Right?
- I think we also need {2} for Area Name to differentiate things.
- Need to see more in depth how Components views are resolved.

So, we need to provide an ordered list as we do for the shape table.

What i've seen for each view is that `ExpandViewLocations()` is called only once , e.g even if you change the tenant. But `PopulateValues()` is always called and can be used to update some contextual values which can be used in our previously provided paths.

We could use this e.g to specify the right theme. But how to implement a different list according to the enabled modules for a given tenant, idem for derived / base themes.

I think i can work on this because it's related to what i've began on `Views/Shared/Shapes`.

**Comment by jtkech** [comment]
I could get it working, not so easy but very interesting, here my findings.

- After `GetExtensions()` to get a 1st ordered list by dependencies and priority we need to use `GetExtensions().Features`. Note: **we still need to fix themes implicit dependencies**.

- Then we have to select only main features which have the same id as the extension they belong.

- Then views path are parsed from the beginning of the list, so we have to `Reverse()` the order.

- Then we need to remove the 2 first provided paths, e.g `/Modules/{2}/Views/{1}/{0}.cshtml`. Otherwise, overriding by another module will not be possible.

- Then we can do what we want. Right now in my tests, if an extension id is equal to the area name (retrieved from `ViewLocationExpanderContext`) i use regular views / components paths. Otherwise i use the same paths but, to differentiate things, under a folder related to the area we want to override.

    E.g if a module define this component.

        \Modules\Orchard.ContentTypes\Views\Shared\Components\SelectContentTypes\Default.cshtml

    It can be overriden by

        \Modules\Orchard.Demo\Views\Orchard.ContentTypes\Admin\Components\SelectContentTypes\Default.cshtml

    Or by this one

        \Modules\Orchard.Demo\Views\Orchard.ContentTypes\Shared\Components\SelectContentType\Default.cshtml

Best.
