### ISSUE TITLE
Orchard 2 vs Orchard Core

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Orchard2#528]
The name Orchard 2 is not growing on me, and Orchard Core 1.0 sounds much nicer.... what do you prefer?

@agriffard said his favourite is "Hard Core CMS".... but im not so sure on that one :)

**Comment by DanielStolt** [comment]
I don't like Orchard 2 either. 

Orchard Core is much better, because it clearly indicates its relationship with ASP.NET Core. But it also has a couple of problems:

- trying to ride the ".NET Core" wave, but what happens when MS marketing geniuses once again decide to rebrand, will the reference to the ".NET Core" wave of products feel as fresh in a few years?
- overloaded, we often talk about for example whether something should be in "core" or not, meaning should it be in the product distribution
- there's a VS project called `Orchard.Core` in Orchard 1.x

Whatever name we choose I think:

- it should definitely have "Orchard" as part of the name
- it should not have a number as part of the name, we should leave that to SemVer versioning
- we should start over with the versioning, so the first release should be 1.0.0.

"Hard Core CMS" might be a little too illicit sounding.. 😄 

I would love to name it something that clearly alludes to the fact that, while it is still clearly Orchard with the best of all its principles and philosophies, it is also a complete rebirth and re-imagining of it, something that is starting fresh.

So hereby I am throwing my suggestion "**Orchard Genesis**" into the mix! :)

**Comment by jersiovic** [comment]
Orchard Mecano CMS ?

**Comment by jersiovic** [comment]
Orchard Construct CMS
Orchard Construct Framework

**Comment by agriffard** [comment]
Graft Cms

**Comment by agriffard** [comment]
https://en.wikisource.org/wiki/1911_Encyclop%C3%A6dia_Britannica/Orchard
ORCHARD (O. Eng. ort-geard, later orceard; a combination apparently of Lat. hortus, garden, and “yard” or “garth”), a piece of ground enclosed for the purposes of horticulture.

**Comment by sebastienros** [comment]
Not sure we should try to add one more probably bad noun to the title (genesis, meccano, blah). Also think we should keep the Orchard lineage.
Core will probably never be dropper until there is a new framework, let;s say 10 years. It's in all the namespaces.
Agreed with the fact it should not have the number in it. This is Orchard, just a new major version.

Orchard Core - free, open source, modular SaaS framework for ASP.NET Core.
Orchard Core CMS - free, open source, fast, modular and multi-tenant Content Management System built on ASP.NET MVC Core.

We could also want to reflect this in the namespaces, for both the framework and the CMS, also reflecting what ASP.NET does:
- OrchardCore
- and OrchardCore.Cms

Just a thought if people think it's valuable.

**Comment by Piedone** [comment]
Why not just keep Orchard and specify the version as 2.0? As it happened with all the other releases?

**Comment by sebastienros** [comment]
@Piedone We had a meeting yesterday, it seems everyone agreed with this change. Watch it.

**Comment by agriffard** [comment]
Discussed again during Tuesday meeting: 
There could be some renaming (Repo, Project, Namespaces) once the big PRs (on which @Jetski5822 @jtkech and @sebastienros are working on : `mvless`, `modular`) are merged.

**Comment by pdxl** [comment]
Corechard??

**Comment by Jetski5822** [comment]
Lol

**Comment by Jetski5822** [comment]
Orchard Core.

**Comment by okouatli** [comment]
How about Orcas?
O = Orchard
R = Redesign
C = Core
A = ASP.NET
S = System
