### ISSUE TITLE
How can I mark that a class is related to a feature?

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#630]
I want to provide two features within a module. I know how to reflect it in module.txt but I don't find an annotation to say that a controller should be enabled if a feature is enabled.
Only thing I see is `ModuleService.GetAvailableFeaturesAsync()` but maybe it is too much to retrieve all the features just to check if one feature is enabled.

Is this a To-Do?

**Comment by jersiovic** [comment]
Most simple solution seems that IModuleService provides a method to evaluate the state of a feature and each module Startup registers those services related with its enabled features.
Only doubt is how do we act for controllers, currently they are automatically registered.

**Comment by Jetski5822** [comment]
The Controller is a Feature right? Features have a Dependencies: attribute against them?

**Comment by Jetski5822** [comment]
[OrchardFeature("Foo")]

**Comment by sebastienros** [comment]
That is the correct way, if it doesn't work we'll fix this bug but it should already bee handled, @jtkech has tried it.
You should also do it for your `Startup` if you need, so you get several of them.
And new in O2, you can add a service/controller for a feature that is defined in another module, so that if the module is there then the matching feature will be enabled automatically. Example Tokens provides services in different modules, but a single feature is defined.

**Comment by sebastienros** [comment]
Please reopen if there is a bug with the feature.
