### ISSUE TITLE
Infos about updates on Auth, Identity, Cookies with AspnetCore 2.0

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard2#730]
@jersiovic @PinpointTownes just for infos.

Working on the razor-page branch we use an aspnetcore 2.0 preview version. When trying to use the last packages by using `2.0.0-preview*`, i saw some updates around `Identity, Cookies ...`, new services extensions ... I could do some updates but not all, just to be able to build and to do my tests.

Maybe you already know this, otherwise i think there are not so much updates to do. Not urgent at all for me, but maybe better that you know this, then you will have more time to update the code.

For infos it's when i tried to use the nightly built `2.0.0-preview*` versions on all `Microsoft.AspNetCore...` and `Microsoft.Extensions...` packages, and from this feed.

    https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json

Best.

**Comment by PinpointTownes** [comment]
@jtkech thanks for the heads-up.

Due to [the massive breaking changes in ASP.NET Core 2.0's authentication stack](https://github.com/aspnet/Security/issues/1179), all the authentication components written for 1.0/1.1 (including OpenIddict, ASOS and the OAuth2 extensions) no longer work and will have to be rewritten to use the new services.

Last week, I started porting ASOS (the OIDC framework behind OpenIddict) and the OAuth2 extensions to this new stack to ensure everything we need is there, but OpenIddict itself still needs some love to work with these changes. I'm not sure yet I want to maintain two code bases (one for 1.0, one for 2.0) until everything is stable.

Do you have an approximate timeline for the 1.1 -> 2.0 migration in Orchard?

**Comment by jtkech** [comment]
Ok, i understand.

Sorry for the timeline, i don't know but my feeling is that we may use 2.0 soon because @sebastienros want to use the new Razor Pages, but this needs to be confirmed by him.

**Comment by sebastienros** [comment]
We might start on preview2 (not before) unless some big pieces are still missing which will have us wait for closer to release.

**Comment by PinpointTownes** [comment]
Sounds fine. We'll likely have nightly builds available at this period.

**Comment by PinpointTownes** [comment]
On a related note, we'll have to come up with a better automatic authentication strategy when moving to 2.0, as this feature - the way the knew it - was removed.

**Comment by sebastienros** [comment]
> automatic authentication strategy 

What is that?

**Comment by PinpointTownes** [comment]
> What is that?

A way to determine whether a given request should use cookie or token authentication, so that `HttpContext.User` is populated using the corresponding principal.

Currently, when both the users and OpenID modules are enabled, automatic authentication is enforced for both the cookies middleware and the JWT/validation middleware and we rely on the end user to decorate his/her API controllers with `[Authorize(ActiveAuthenticationSchemes = "Bearer")]` to make sure a "cookies identity" is not used to populate `HttpContext.User` (which would result in a XSRF flaw otherwise).

This strategy doesn't work well because users are still seeing 401 -> 302 redirections (kicked in by Identity) even if we use this attribute (see https://github.com/OrchardCMS/Orchard2/issues/726#issuecomment-297884305 for a concrete example that involves the userinfo endpoint). In 2.0, "dual authentication" won't be possible and we'll have to find a way to fix that.

**Comment by sebastienros** [comment]
NB: "his/her" -> "their"

**Comment by PinpointTownes** [comment]
> NB: "his/her" -> "their"

Nah, I think I'll take the risk of being accused of sexism and use just "his" :trollface: 

On a more serious note, I added the `Orchard.Users` label as this module will also be impacted by these changes.

**Comment by PinpointTownes** [comment]
OpenIddict and aspnet-contrib packages compatible with the ASP.NET Core 2.0 preview3/RTM nightly builds are now available and can be downloaded from the aspnet-contrib MyGet feed.

I'm closing this issue since everything has been resolved on my end.

**Comment by jtkech** [comment]
Cool
