### ISSUE TITLE
If password contains minus, space or underline it stored incorrectly

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/Orchard2#739]
So that login then impossible

**Comment by sebastienros** [comment]
Better issue description: https://github.com/OrchardCMS/Orchard2/issues/817

**Comment by xperiandri** [comment]
It was completely my mistake of trying to put email instead of user name.
Maybe it will be nice to allow to login by email as well?

**Comment by sebastienros** [comment]
What's weird is that there are limitations on the username. Either that's an issue or we need to validate it.

**Comment by xperiandri** [comment]
What do you mean about limitations?

**Comment by sebastienros** [comment]
I thought you meant you could not use an email in the username field. Now I understand what you meant, that you used the email instead of the username when you tried to log.
We can't use the email too as we are not assessing the unicity of emails against usernames. Meaning there could be collisions and security issues with collisions between usernames and emails. Say you have the andreii@gmail.com email, and andreii as a username. I could create a username with andreii@gmail.com and then potentially impersonate your account. Not saying it's not doable but there are risks we don't realize we are adding some attack vectors.

**Comment by Skrypt** [comment]
@sebastienros the thing here is that Accounts normally gets "activated" through sending an email to verify if this email is valid. So, normally, accounts are verified through emails. Which means that an Account on the website will always be strongly attached to a specific email. I believe that if you register a new account you should verify for unique usernames and also unique emails to prevent impersonation to happen. Though, a user could want to edit his email address from his profile, or an admin could want to change the email associated to a user account. In that case I believe that we should verify if the email has not been already assigned to any other user account. That way, the username becomes only a "shortener" for the login if it's actually shorter than the user email. Somehow, login from the email or the username in the end should do the same if Email + Username are unique for each accounts.

**Comment by Jetski5822** [comment]
I kinda feel we should have unicity on email so you can long in with either... don't you think? Most sites allow login with either
