### ISSUE TITLE
The Indexing_Task table is not populated on setup

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#746]
Maybe the module is enabled too late?

**Comment by yiji** [comment]
need background task setting module,now task excute too frequently，it‘s best can custom setting excute period

**Comment by jtkech** [comment]
Maybe because there is not yet e.g a lucene index. Didn't see in the code an index command that we could use as a command step. And not sure that we can already use a command step in a recipe.

**Comment by sebastienros** [comment]
this table is independent from lucene indices, it's in its own module.

**Comment by jtkech** [comment]
Okay.

It seemed to me that to be able to see something in this table i needed to create an index. But just remember that i also re-published a page which could explain this.

I will take a look more in depth.

**Comment by jtkech** [comment]
Here my first findings.

So, in a content step an item is created with `options.IsPublished`, `Published` handlers are called and then `IndexingTaskManager.CreateTaskAsync()`. But because `contentItem.Id == 0`, no new `IndexingTask` is created. Here, the comment i can see in the code.

    // Ignore that case, when Update is called on a content item which has not be "created" yet

If i remove the `contentItem.Id` checking it works, the table is populated,  but not sure we can do that.

**Comment by sebastienros** [comment]
Thanks for looking at it, don't try to change anything until we understand the "Ignore that case" reason. What I saw is that we might want to change how the content is imported, it should not force `Published`.

**Comment by jtkech** [comment]
Okay cool, i understand.
