### ISSUE TITLE
Can not create OpenId Application and there are no Flows available

### ISSUE THREAD

**Issue by rserj** [OrchardCMS/Orchard2#777]
While adding new open Id Client application Web UI always required Client Secret. Even if it is filled.
The Client Secret is required - always appeared.
http://prntscr.com/fcvqg9

Plus Flows are empty (see above screenshot), there are no Flows in Design->Settings->OpenID Connect settings too, even If all endpoints selected http://prntscr.com/fcvr6r.

**Comment by jersiovic** [comment]
Empty flows in setting were fixed recently on this PR https://github.com/OrchardCMS/Orchard2/pull/769, can you repro that on the head of master?

I will check the other issue with Client Secret

**Comment by jersiovic** [comment]
Adding a new OpenId Client app worked initially properly for me. However, if I use a short password I experience same problem you describe.
Currently Client Secret property has this validation attribute: [StringLength(100, MinimumLength = 6)] that's why you get this error. So, by the moment you can use a longer a Password.

To-Do in OpenId module: To move attibute validation to controller for providing more specific and localizable validation messages
