### ISSUE TITLE
NLog.config not copied to publish folder

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/Orchard2#829]
When running dotnet publish on Orchard.Cms.Web, Nlog.config is not published. Is this by design, or should this be included? Happy to submit PR.

Addition to \src\Orchard.Cms.Web.csproj:

~~~~
  <ItemGroup>
    <Content Include="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
~~~~

**Comment by jtkech** [comment]
You're right, e.g all `*.json` are published but only `web.config`.

Because `Orchard.Cms.Web` reference the `OrchardCore.Cms` bundle, some of our custom scripts are evaluated. See in `OrchardCore.Cms.props` and in `OrchardCore.AsBundle.targets` how we define publish outputs for `App_Data\` and `Packages\`. We do this in a custom way so these items are published but not displayed in the VS solution, e.g there may be too many site folders under `App_Data\`.

    ...
    <ItemGroup>
      <ResolvedFileToPublish Include="App_Data\**" Exclude="App_Data\**\*.log">
        <RelativePath>App_Data\%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
      </ResolvedFileToPublish>
    </ItemGroup>

    ...
    <ItemGroup>
      <ResolvedFileToPublish Include="Packages\**">
        <RelativePath>Packages\%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
      </ResolvedFileToPublish>
    </ItemGroup>

But, you're right, `Orchard.Logging.NLog` is referenced by `Orchard.Cms.Web`, so seems to be the right place to add `NLog.config` to the publish outputs, and in a regular way so not hidden from the solution.

But we don't need to copy this file to the output directory `bin\Debug\netcoreapp1.1` we just need to output it on publishing, **so i suggest the following as it is done by msbuild** e.g for `web.config` files.

    <ItemGroup>
      <Content Include="NLog.config" CopyToPublishDirectory="PreserveNewest" />
    </ItemGroup>

**Comment by sebastienros** [comment]
Correct solution, in the CMS bundle.

**Comment by jtkech** [comment]
Ok, so we just need to add it to `OrchardCore.Cms.props`.

Then, is it better to reference `Orchard.Logging.NLog` in `OrchardCore.Cms.csproj`?
Or let `Orchard.Logging.NLog` referenced in `Orchard.Cms.Web.csproj`?

**Comment by sebastienros** [comment]
no you are right, ORchard,Cms.WEb, wherever we reference NLog

**Comment by jtkech** [comment]
Ok, let @anoordende doing it.

**Comment by anoordende** [comment]
Ok, will do.
