### ISSUE TITLE
Orchard T(wo) should natively use bootstrap

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard2#87]
And fixe some common options already subject of discutions in Orchard One.
Resources, pluggable Admin theme, etc,

**Comment by sebastienros** [comment]
Feel free to open issue for every suggestion so we can track discussions for each of them.

**Comment by CSurieux** [comment]
Even the icecream generator ?

**Comment by AlbertoLeon** [comment]
I think it should be open to implement custom admin themes not required Bootstrap. Did you see Material? And there are some other choices... I think it is better to have a very clean base, an alternative for bootstrap, but leave it open to other UI libraries.

**Comment by CSurieux** [comment]
Yes but the clean base is not necessary, we should be able to select 'work in bootstrap mode or work in xxx mode' from scratch without a base. The actual less option in Orchard is useless as soon as you make something more complicated than simply displayin the layout-main div, it adds many useless elements and it is quite impossible to use it for more complexe cases than layout.cshtml. So why don't says we generate in many 'html/css frameworks' and each framework community is in charge of providing its templates.

**Comment by sebastienros** [comment]
So the question is what should the default theme be? And should there be more default theme?

**Comment by CSurieux** [comment]
Refering to the Feel free invitation, why closing points needing a broader discussion and more time (point #90) ?

**Comment by anoordende** [comment]
Just thinking out loud, but I agree with squeaky-clean. How about absolutely zero class references in any core/module templates? With a framework such as Bootstrap ("soon" to be v4 using SASS - not LESS) the key is complete control on css classes, which means overriding shapes/parts/templates.

Then, we (ie. the community) can supply standard UI Framework base themes (along the lines of what @CSurieux commented) that override the necessary templates targeting a specific UI Framework. Possibly a BS v4 UI Framework base theme can come as part of the out-of-the-box experience, but quite rightly Material is also a great candidate as mentioned by @AlbertoLeon.

Custom theme authors can choose to either use a UI Framework base theme or completely write their own overrides if they find the base theme too restrictive. Key is, of course, that Orchard itself adds as little as possible noise.

With regards to a default theme, the out-of-the-box "ThemeMachine" should be based on one of these UI Framework base themes, quite arbitrarily. Overall what I am trying to say is that the theme should be responsible for the classes being rendered, instead of Orchard dictating to the theme what classes to use.

Having a UI Framework base theme however comes with some additional challenges. For example, bootstrap "requires" adding style-specific classes:

`<nav class="navbar navbar-light bg-faded">`

Even in a framework base theme we can't assume which navbar style to apply, because the css classes are style-specific and not function-specific, so the theme author must either override this template or e.g. extend or completely override the class in their custom (SASS) stylesheet:

`
.layout-header {
    .navbar {
        @extends .navbar-light;
    }
}
`

Though this would arguably add lots of useless overhead to an already bloated BS stylesheet (no pun intended). Another option is configuring this through the Admin UI (after all, we can already set the css class), but I'm not a fan of database-driven themes.

And yes, this does also imply that custom module authors must keep their templates free of style galore and instead target specific frameworks (or no styles at all) in their templates. Hell yeah for the standardisation that would introduce!.

In Orchard v1 I am working on a similar solution with a base theme containing template overrides organised by UI framework, which works in combination with a ShapeTableProvider to add alternates, e.g. Part_Menu_Bootstrap. Currently this hijacks a theme's Tags setting to select the right framework, but in v2 "Framework" could easily be a setting of a theme. This setting can then also be used to select the right framework template from custom modules.

For me personally, if a new Orchard site started up without any styles, I'd be happy. But I understand that that doesn't sell very well to newcomers.

Magic :8ball: says it's time for a beer.

**Comment by Skrypt** [comment]
Use of webcomponents could make this possible.
```
<style>
  google-map {
    height: 600px;
  }
</style>
<google-map latitude="37.77493" longitude="-122.41942"></google-map>
```

I think this is where the web leans to. Maybe we should take in consideration to use something like Polymer.
https://www.polymer-project.org/1.0/
I'm not sure though if it is too early to adopt something like this.

**Comment by CSurieux** [comment]
@anoordende  I finally agree with your development, being only a bootstrap user I don't know the other challengers but sometime I also think BS is heavy to drive.
The second point I would introduce is that the MVC model is finally not perfect for web (I already hear the MVC wolfs howling and mocking my steps): when you have generated your data in the controller/driver you must keep with what has been done in your view/template and many time it is a serious limitation...
