### ISSUE TITLE
OpenId Audience validation failed

### ISSUE THREAD

**Issue by rserj** [OrchardCMS/Orchard2#870]
I tried to use Password flow, I created my API but when I tried to invoke it, Audience validation failed

IDX10214: Audience validation failed. Audiences: 'empty'. Did not match: validationParameters.ValidAudience: 'null' or validationParameters.ValidAudiences: 'https://localhost:44301'.

It happens because in configuration while registering middleware we set ValidateAudience = true

`.UseJwtBearerAuthentication( new JwtBearerOptions {
     TokenValidationParameters = new TokenValidationParameters
                        {
                             ValidAudiences = settings.Audiences,
                             ValidateAudience = true
                        }
})`

but we do not Issuing "aud" claim in Token end-point.
I guess we should issue aud claim per OpenId App? If so we need to store it per OpenId App
(Like Origins in this PR https://github.com/OrchardCMS/Orchard2/pull/849)

**Comment by Jetski5822** [comment]
@jersiovic assigned you, any ideas?

**Comment by jersiovic** [comment]
Well if you set ValidateAudience = true in JwtBearerOptions then I think Orchard will need to issue aud claim for any OpenId app, so you don't need to store it at openid app level. So I would add a new property ValidateAudience to OpenIdSettings to decide the value of ValidateAudience on startup and also to decide if an aud claim needs to be issued or not on AccessController.CreateTicketAsync()

I'm not an expert and I have not used OpenIddict with ValidateAudience = true, if it doesn't work maybe @PinpointTownes can provide more expertise advice.

**Comment by PinpointTownes** [comment]
> Well if you set ValidateAudience = true in JwtBearerOptions then I think Orchard will need to issue aud claim for any OpenId app, so you don't need to store it at openid app level.

It already does that, but only if you specify a `resource` parameter containing the audiences you want (typically, at least one of the audiences specified in the options): https://github.com/OrchardCMS/Orchard2/blob/master/src/OrchardCore.Modules/Orchard.OpenId/Controllers/AccessController.cs#L356

We can - and should - definitely improve that because the default experience is less ideal than with opaque tokens. One thing we could do is use `settings.Audiences` when no `resource` parameter is specified.
