### ISSUE TITLE
How Orchard.User module extensive?

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/Orchard2#888]
In User module , the type of user could not be added other part ? how user type extensive ? i want user type more information.

**Comment by rserj** [comment]
You can not extend existing User because of Yes SQL restriction, per discussion with @sebastienros it will be improved in the future.
But there is a PR https://github.com/OrchardCMS/Orchard2/pull/810
Which is replacing User to -> IUser, so you may create your own User implementation and override ASP.NET Identity services.

**Comment by jnucpz** [comment]
ok.thank you for your answer
