### ISSUE TITLE
Provide root objects in liquid from services

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#979]
Create and extensible way to provide root properties in a template context.
To be able to use `Queries.RecentBlogPosts` for instance. Could be used also for `User`, `Site` which would then be provided by their respective modules.

**Comment by jtkech** [comment]
Yes, we need this.

- So, these modules will need to reference `Liquid.Abstractions`, right?.

- Then, we could have `ILiquidValuesProvider` services to add local scope values and strategies.

- I also think about `ILiquidTypesProvider` to only add local strategies for types known by a module but whose values will belong to the Model (e.g `Fields`). But here, maybe better to add **global** strategies.

- But i think we don't allow a module to add or request to add a **global** strategy, because if the module is disabled, the strategy would be kept. But maybe yes for fields defined in `O.ContentFields`...

**Comment by sebastienros** [comment]
Start with `ILiquidValueProvider` in abstractions. And it's called like filters are when a context is built.
Move `User` and `Site` to their respective modules. Scoped services.

**Comment by jtkech** [comment]
Okay cool, i will do a PR.
